### ISSUE TITLE
Dropbox backups not beign executed in odoo11 docker container

### ISSUE THREAD

**Issue by nehemiascr** [cytex124/odoo-automatic-backup#10]
I installed the module in the official docker container for odoo 11, I ave schedules dropbox daily backups but they never get executed, If I click manually the Backup button it works fine, I tried deleting the Backup Configuration and creating it again but still the backup configurations doesn't execute, what can I do ? thanks

**Comment by nehemiascr** [comment]
```bash
2018-03-02 13:36:29,628 1 INFO uccart odoo.addons.base.ir.ir_cron: Starting job `Backup: Respaldo diario en dropbox`.
2018-03-02 13:36:29,635 1 ERROR uccart odoo.addons.base.ir.ir_cron: Call from cron Backup: Respaldo diario en dropbox for server action #270 failed in Job #5
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/safe_eval.py", line 348, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/mnt/extra-addons/automatic_backup_to_whatever/models/models.py", line 176, in action_backup
    backup_ids = self.search([id])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1407, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3670, in _search
    if expression.is_false(self, args):
  File "/usr/lib/python3/dist-packages/odoo/osv/expression.py", line 224, in is_false
    elif token[1] == 'in' and not token[2]:
TypeError: 'int' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_cron.py", line 101, in _callback
    self.env['ir.actions.server'].browse(server_action_id).run()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_actions.py", line 541, in run
    res = func(action, eval_context=eval_context)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_actions.py", line 417, in run_action_code_multi
    safe_eval(action.sudo().code.strip(), eval_context, mode="exec", nocopy=True)  # nocopy allows to return 'action'
  File "/usr/lib/python3/dist-packages/odoo/tools/safe_eval.py", line 371, in safe_eval
    pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/odoo/tools/safe_eval.py", line 348, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/mnt/extra-addons/automatic_backup_to_whatever/models/models.py", line 176, in action_backup
    backup_ids = self.search([id])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1407, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3670, in _search
    if expression.is_false(self, args):
  File "/usr/lib/python3/dist-packages/odoo/osv/expression.py", line 224, in is_false
    elif token[1] == 'in' and not token[2]:
ValueError: <class 'TypeError'>: "'int' object is not subscriptable" while evaluating
'model.action_backup(1)'
2018-03-02 13:37:14,247 1 INFO uccart werkzeug: 181.194.116.145 - - [02/Mar/2018 13:37:14] "POST /longpolling/poll HTTP/1.1" 200 -
```

**Comment by cytex124** [comment]
Hi,

I have a workaround for your problem:
Go to the backup (the backup form) and copy the ID of this dataset. You can find it in the URL under "#id=**_your id_**&view_type=...".
Go to settings-->automatic action-->to your "Backup: _Dropbox_" or just click on "cron" in the backup-from. There you can find the execution code "model.action_backup(1)". Change it to model.action_backup(**_your id_**).

It look like odoo can´t find the dataset of the backup-model. But I don´t really understand why the automatic-action points to dataset 1. In your case it should be 2.

Let me know, if it works.

Best regards,

Andy

**Comment by nehemiascr** [comment]
Thank you for your explanation, the id of the dataset is being correctly stored in the cron job, I solved this error by changing the use of search() for browse() in the action_backup() method when retrieving the backup records. https://github.com/cytex124/odoo-automatic-backup/pull/11

**Comment by cytex124** [comment]
Thy for ur help! I will check ur pull request soon.
