### ISSUE TITLE
I have the same issue as #15

### ISSUE THREAD

**Issue by odooconcept** [cytex124/odoo-automatic-backup#24]
After pasting the module in the addons folder Odoo and 
all requirements  successfully installed with command "pip install -r requirements.txt", I restarted the server but Odoo displays just a blank page with  the logo.

The log displays following error:
2018-10-22 13:14:32,609 1230 INFO ? odoo: Odoo version 11.0
2018-10-22 13:14:32,611 1230 INFO ? odoo: Using configuration file at /etc/odoo-server.conf
2018-10-22 13:14:32,611 1230 INFO ? odoo: addons paths: ['/odoo/.local/share/Odoo/addons/11.0', '/odoo/odoo-server/addons', '/odoo/custom/addons', '/odoo/odoo-server/odoo/addons']
2018-10-22 13:14:32,612 1230 INFO ? odoo: database: default@default:default
2018-10-22 13:14:32,697 1230 INFO ? odoo.service.server: HTTP service (werkzeug) running on ubuntu-xenial-4.c.odoo-concept-wp-site.internal:8069
2018-10-22 13:14:33,510 1230 INFO ? odoo.addons.base.ir.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/bin/wkhtmltopdf
2018-10-22 13:14:34,717 1230 WARNING ? odoo.addons.base.res.res_currency: The num2words python library is not installed, l10n_mx_edi features won't be fully available.
2018-10-22 13:14:35,038 1230 INFO ? werkzeug: 181.196.72.57 - - [22/Oct/2018 13:14:35] "GET /web?debug=1 HTTP/1.1" 500 -
2018-10-22 13:14:35,129 1230 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 270, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 258, in execute
    application_iter = app(environ, start_response)
  File "/odoo/odoo-server/odoo/service/server.py", line 250, in app
    return self.app(e, s)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/odoo/odoo-server/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/odoo/odoo-server/odoo/http.py", line 1317, in __call__
    self.load_addons()
  File "/odoo/odoo-server/odoo/http.py", line 1349, in load_addons
    m = __import__('odoo.addons.' + module)
  File "/odoo/odoo-server/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 3, in <module>
    
  File "/odoo/odoo-server/addons/automatic_backup_to_whatever/models/__init__.py", line 3, in <module>
    from . import models
  File "/odoo/odoo-server/addons/automatic_backup_to_whatever/models/models.py", line 6, in <module>
    import boto3
ImportError: No module named 'boto3'

ODOO CONFIG FILE:

[options]
addons_path = /odoo/odoo-server/addons,/odoo/custom/addons
admin_passwd = $pbkdf2-sha512$25000$BUCo9f6fk3JOyZlz7j1n7A$LivcMtRVVxESGY40FuefgAy235X.9hfBcP6sO5l.hiIqxzcpmUqmRlommwhQyTHqXK6CcPmvgc8x/PMjnBcqPg
csv_internal_sep = ,
data_dir = /odoo/.local/share/Odoo
db_host = False
db_maxconn = 64
db_name = False
db_password = False
db_port = False
db_sslmode = prefer
db_template = template1
db_user = False
dbfilter = 
demo = {}
email_from = False
geoip_database = /usr/share/GeoIP/GeoLite2-City.mmdb
http_enable = True
http_interface = 
http_port = 8069
import_partial = 
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 60
limit_time_real = 120
limit_time_real_cron = -1
list_db = True
log_db = False
log_db_level = warning
log_handler = :INFO
log_level = info
logfile = /var/log/odoo/odoo-server.log
logrotate = False
longpolling_port = 8072
max_cron_threads = 2
osv_memory_age_limit = 1.0
osv_memory_count_limit = False
pg_path = None
pidfile = None
proxy_mode = False
reportgz = False
server_wide_modules = web
smtp_password = False
smtp_port = 25
smtp_server = localhost
smtp_ssl = False
smtp_user = False
syslog = False
test_commit = False
test_enable = False
test_file = False
test_report_directory = False
translate_modules = ['all']
unaccent = False
without_demo = False
workers = 0

**Comment by cytex124** [comment]
Read the error message. 
Install all requirements from the .txt file
