### ISSUE TITLE
Error: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by florianbepunkt** [cytex124/odoo-automatic-backup#9]
Hi,

I use the Odoo bitnami stack on Amazon AWS. I installed the requirements as described in this repo's readme.

I tried to backup to a S3 bucket. When running the backup job it reads: `maximum recursion depth exceeded while calling a Python object` I get the email that the backup was sucessfull (in the subject) with the same error. No backup was made.

Any idea what might cause this?

**Comment by cytex124** [comment]
can you please paste the stacktrace? - It´s hard to find the problem without it.

thanks!

**Comment by florianbepunkt** [comment]
@cytex124 sure. can you direct me where to find the right logs?

**Comment by florianbepunkt** [comment]
@cytex124 reason I am asking is that there is no error message in the general odoo logs: this is all there is… which is no error message at all.

```
2018-03-02 18:54:59,041 1417 INFO Strike odoo.service.db: DUMP DB: Strike format zip
2018-03-02 18:55:03,042 1417 INFO Strike botocore.vendored.requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): strikedout.s3.amazonaws.com
2018-03-02 18:55:03,249 1417 INFO Strike odoo.addons.mail.models.mail_mail: Mail with ID 20 and Message-Id '<373364267225362.1520016903.120696544647217-openerp-1-automatic_backup_to_whatever.configuration@ip-168-28-9-204>' successfully sent
2018-03-02 18:55:03,261 1417 INFO Strike odoo.models.unlink: User #1 deleted mail.mail records with IDs: [20]
2018-03-02 18:55:03,277 1417 INFO Strike odoo.models.unlink: User #1 deleted mail.message records with IDs: [133]
2018-03-02 18:55:03,277 1417 INFO Strike odoo.addons.mail.models.mail_mail: Sent batch 1 emails via mail server ID #False
```

**Comment by cytex124** [comment]
@florianbepunkt can you maybe reproduce it manually and send me the stracktrace shown in the webbrowser. should be the same as in the logs.

**Comment by florianbepunkt** [comment]
Not sure if I understood you correctly. There is no stacktrace other than what I have posted. Except the message it says that the backup was successful.

**Comment by cytex124** [comment]
@florianbepunkt ok. I will check it in the next days. Also I will make a update to get clear exceptions.

can you please also send me your policy of the iam user?

**Comment by florianbepunkt** [comment]
attached a group policy to allow full s3 access:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": "*"
        }
    ]
}

Interesting thing…I created a new user for backup tasks. The IAM dashboard says that this user was never used. Double checked the credentials… they are correct.
```

**Comment by rwngallego** [comment]
I'm having this same problem while using dropbox and executing a Manual backup. I'm using Odoo 11:

`maximum recursion depth exceeded while calling a Python object`

**Comment by cytex124** [comment]
I made some changes in the code. Can u please pull the newest version. If the error still exists you should now get an error with the stackstrace. Please post it. 

Sorry I really can´t reproduce it. So I need your help. :)

**Comment by florianbepunkt** [comment]
@cytex124 just heading out. but will check tomorrow and report back. thank you.

**Comment by rwngallego** [comment]
Hi @cytex124 I've updated Odoo from version 11.0-20171218 to 11.0-20180218 and the problem has disappeared.

I've checked on a server with the old Odoo version and your latest changes, and the error is the same: 

`maximum recursion depth exceeded while calling a Python object`

**Comment by florianbepunkt** [comment]
Hi @cytex124, just installed the fix for correct stacktraces. I am also on Odoo 11.0-20180118. Stacktrace below

Fehler:
Odoo Server Error

```
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180118-py3.6.egg/odoo/addons/automatic_backup_to_whatever/models/models.py", line 185, in btn_action_backup
    def set_show_access_key(self):
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180118-py3.6.egg/odoo/addons/automatic_backup_to_whatever/models/models.py", line 215, in _backup_on_s3
    if self.cron_id and self.active:
  File "/opt/bitnami/python/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/bitnami/python/lib/python3.6/site-packages/botocore/client.py", line 599, in _make_api_call
    operation_model, request_dict)
  File "/opt/bitnami/python/lib/python3.6/site-packages/botocore/endpoint.py", line 143, in make_request
    return self._send_request(request_dict, operation_model)
  File "/opt/bitnami/python/lib/python3.6/site-packages/botocore/endpoint.py", line 172, in _send_request
    success_response, exception):
  File "/opt/bitnami/python/lib/python3.6/site-packages/botocore/endpoint.py", line 265, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/opt/bitnami/python/lib/python3.6/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/opt/bitnami/python/lib/python3.6/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/opt/bitnami/python/lib/python3.6/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/opt/bitnami/python/lib/python3.6/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/opt/bitnami/python/lib/python3.6/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/opt/bitnami/python/lib/python3.6/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/opt/bitnami/python/lib/python3.6/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/opt/bitnami/python/lib/python3.6/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/opt/bitnami/python/lib/python3.6/site-packages/botocore/endpoint.py", line 213, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/opt/bitnami/python/lib/python3.6/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/opt/bitnami/python/lib/python3.6/site-packages/botocore/vendored/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/opt/bitnami/python/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/opt/bitnami/python/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/opt/bitnami/python/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/opt/bitnami/python/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/opt/bitnami/python/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/util/ssl_.py", line 263, in ssl_wrap_socket
    ciphers=ciphers)
  File "/opt/bitnami/python/lib/python3.6/site-packages/botocore/vendored/requests/packages/urllib3/util/ssl_.py", line 231, in create_urllib3_context
    context.options |= options
  File "/opt/bitnami/python/lib/python3.6/ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/opt/bitnami/python/lib/python3.6/ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  File "/opt/bitnami/python/lib/python3.6/ssl.py", line 465, in options
    super(SSLContext, SSLContext).options.__set__(self, value)
  [Previous line repeated 276 more times]
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180118-py3.6.egg/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180118-py3.6.egg/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180118-py3.6.egg/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7f2c18859378>, 'automatic_backup_to_whatever.backup_configuration_error_template')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180118-py3.6.egg/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180118-py3.6.egg/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180118-py3.6.egg/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180118-py3.6.egg/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180118-py3.6.egg/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180118-py3.6.egg/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180118-py3.6.egg/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180118-py3.6.egg/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180118-py3.6.egg/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180118-py3.6.egg/odoo/addons/web/controllers/main.py", line 934, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180118-py3.6.egg/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180118-py3.6.egg/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180118-py3.6.egg/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180118-py3.6.egg/odoo/addons/automatic_backup_to_whatever/models/models.py", line 197, in btn_action_backup
    or (self.backup_type == BackupTypes.sftp.value[0])
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180118-py3.6.egg/odoo/addons/automatic_backup_to_whatever/models/models.py", line 202, in send_email
    self.set_show_s3()
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180118-py3.6.egg/odoo/api.py", line 793, in ref
    return self['ir.model.data'].xmlid_to_object(xml_id, raise_if_not_found=raise_if_not_found)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180118-py3.6.egg/odoo/addons/base/ir/ir_model.py", line 1332, in xmlid_to_object
    t = self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180118-py3.6.egg/odoo/addons/base/ir/ir_model.py", line 1316, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-24>", line 2, in xmlid_lookup
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180118-py3.6.egg/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20180118-py3.6.egg/odoo/addons/base/ir/ir_model.py", line 1305, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: automatic_backup_to_whatever.backup_configuration_error_template
```

**Comment by cytex124** [comment]
Ok lets see:
1. Error: Can u please post your installed pip packages. It looks like there is a problem in the botocore lib or the gevent lib. Maybe a dependency is wrong. See also https://github.com/gevent/gevent/issues/903
2. Error: I can see another error appears. A template can´t be found. I already changed the mail-template name from "automatic_backup_to_whatever.backup_configuration_error_template" to "automatic_backup_to_whatever.backup_configuration_error_mail". Can you please look into "Settings-->Technical-->Templates". There you can search for the template. If you can´t find it, please update the module again. I really don´t get why the module is still using the old template name.

**Comment by florianbepunkt** [comment]
thank you. upgrading pip packages gevent and bootcore did the trick.
